USE ad;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `Item`;
DROP TABLE IF EXISTS `ItemCategory`;
DROP TABLE IF EXISTS `Bids`;
DROP TABLE IF EXISTS `User`;
DROP TABLE IF EXISTS `GeoLocation`;
DROP TABLE IF EXISTS `Location`;
SET FOREIGN_KEY_CHECKS=1;